"""Adding categories column in the pitches table

Revision ID: 374daa6f91e9
Revises: 6f372c44d7f7
Create Date: 2018-05-19 23:47:23.621043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '374daa6f91e9'
down_revision = '6f372c44d7f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch_category', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'pitch_category')
    # ### end Alembic commands ###
