"""Removing unique key from the user_id in Upvotes table

Revision ID: c352f6cd9277
Revises: 9ed0172675c3
Create Date: 2018-05-20 16:00:09.991882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c352f6cd9277'
down_revision = '9ed0172675c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('upvotes_id_user_key', 'upvotes', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('upvotes_id_user_key', 'upvotes', ['id_user'])
    # ### end Alembic commands ###
